### ISSUE TITLE
Add developer-facing documentation

### ISSUE THREAD

**Issue by jwodder** [dandi/dandidav#148]
* [x] Write a document covering the basics of the WebDAV protocol (#151)
* [x] Write a document outlining the program's architecture (#166)
* [x] Write a document on the release process for this project (#149)
* [x] Write a document describing the requirements for the Zarr manifests and their index (#163)

Place all documents in `doc/`.
