### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by jwodder** [dandi/dandidav#5]
- [ ] Log the bodies & "Depth" headers of all accepted `PROPFIND` requests
- [ ] Log `PROPFIND` requests rejected due to infinite or invalid "Depth" headers
- [ ] Log `PROPFIND` requests rejected due to invalid request bodies
- [x] Log all errors (with cause chains) that result in 5xx responses (#63)
- Log the reasons for 404 responses
    - [x] Log errors that reach the top level and result in 404's (#63)
    - [ ] Log all errors that are converted to 404's before reaching the top level
    - [ ] Log 404's caused by a function returning `None`
    - [ ] When a request is received for an invalid/unrecognized path, log that this is what is happening
- [x] Log all Dandi Archive API requests (#58)
- [ ] Log all S3 requests
- [ ] Try to improve the log display format?
- [ ] Enable tracing for `moka` (which uses `log`)
    - Problem: https://github.com/tokio-rs/tracing/discussions/2875
- [x] Do not log SSL details for HTTPS requests made by the server (#58)
- [ ] Use [`tracing-unwrap`](https://docs.rs/tracing-unwrap) to log failed unwraps/expects?
